/////////////////////////////////////////////////////////////////////////////
/**
    \file ChildFrame.h
    Interface of the ChildFrame class.

    \author George J. Grevera, Ph.D., ggrevera@sju.edu

    Copyright (C) 2002, George J. Grevera

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
    USA or from http://www.gnu.org/licenses/gpl.txt.

    This General Public License does not permit incorporating this
    code into proprietary programs.  (So a hypothetical company such
    as GH (Generally Hectic) should NOT incorporate this code into
    their proprietary programs.)
 */
#if !defined(AFX_CHILDFRAME_H__56F32C2D_9870_4275_87AA_467CCDB6ADA3__INCLUDED_)
#define AFX_CHILDFRAME_H__56F32C2D_9870_4275_87AA_467CCDB6ADA3__INCLUDED_

#if _MSC_VER > 1000
  #pragma once
#endif // _MSC_VER > 1000

/** \brief ChildFrame class.  Automatically generated by Visual C++.
 */
class ChildFrame : public CMDIChildWnd {
	DECLARE_DYNCREATE( ChildFrame )
public:
	ChildFrame();

// Attributes
public:

// Operations
public:

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(ChildFrame)
	virtual BOOL PreCreateWindow ( CREATESTRUCT& cs );
	//}}AFX_VIRTUAL

// Implementation
public:
	virtual ~ChildFrame ( );
#ifdef _DEBUG
	virtual void AssertValid ( ) const;
	virtual void Dump ( CDumpContext& dc ) const;
#endif

// Generated message map functions
protected:
	//{{AFX_MSG(ChildFrame)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code!
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHILDFRAME_H__56F32C2D_9870_4275_87AA_467CCDB6ADA3__INCLUDED_)
